### ISSUE TITLE
Tests meilisearch implementation

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/docs-scraper#32]
These tests only tries communication with MeiliSearch and not the pertinence of the scraper:

Tests should be made to test if MeiliSearch implementations works correctly.

In `meilisearch_helper.py` the following is done:

- Delete the scrape index if it already exists
- Create a new index with the same name
- Add default and custom settings to index

These should be tested if it was done successfully.
You can confirm it worked correctly using the [`GET /indexes` method](https://docs.meilisearch.com/reference/api/indexes.html#list-all-indexes). 

A test directory should be created `meilisearch_***`.

In that directory the different tests should be made
- A simple meilisearch configuration with the right credentials and no setting (#154)
    - Check if index was correctly added to Meilisearch
    - Check if default setting were added correctly 
- A simple meilisearch configuration with the right credentials and settings
    - Check if index was correctly added to Meilisearch
    - Check if default setting were added correctly 
- A simple meilisearch configuration with the right credentials and bad settings
    - Check if index was correctly added to Meilisearch
    - Check if error is raised

To start this tests, their should be a running instance of Meilisearch.

.github/workflows/test-lint.yml
```yaml
      - name: Docker setup
        run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key='masterKey'
      - name: Run tests
        run: pipenv run pytest ./scraper/src -k "not _browser"
```
